// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include <iostream>
#ifndef dff_app_h
#define dff_app_h
#include <FL/Fl.H>
void callback_button( Fl_Widget* widg, void* userdata );
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *input_box;
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Output.H>
extern Fl_Output *output_box;
#include <FL/Fl_Button.H>
#endif
